title: Sagar R Kothari
email: sag333ar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Passionate and enthusiastic iOS application developer having 8 years of experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sagarrkothari.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sag333ar
github_username: SagarRKothari

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll/tagging
  # - jekyll-coffeescript
  # - jekyll-gist
  # - jekyll-github-metadata
  - jekyll-paginate
  # - jekyll-relative-links
  # - jekyll-optional-front-matter
  # - jekyll-readme-index
  # - jekyll-default-layout
  # - jekyll-titles-from-headings
  # - jekyll-redirect-from
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-avatar
  # - jemoji
  # - jekyll-mentions
keep_files: ["assets"]

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Tagging related
# tag_page_layout: tag_page
# tag_page_dir: tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
